# build environment
FROM node:10 as builder

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json /app/package.json

RUN npm install --silent
RUN npm install react-scripts@2.1.3 -g --silent

COPY . /app
RUN npm run build

# production environment
FROM nginx:1.13.9-alpine

RUN rm -rf /etc/nginx/conf.d

COPY conf /etc/nginx

COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]